channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser~=4.0
  # Specify major version of jupyter lab
  - jupyterlab>=4.5,<5
  # Provides memory useage stats on JupyterLab
  - jupyter-resource-usage>=1.2.0
  - ipykernel=7.2

  # Set default python version to 3.11 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.11
  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller~=1.2


  # Core scientific python stack
  - cython=3.2
  - numpy=1.26
  - pandas=3.0
  - scipy=1.17
  - xarray=2026.2
  - flox=0.11

  # Visualization packages
  - matplotlib=3.10
  - imageio=2.37
  - cmocean=4.0
    
  # Geospatial data packages
  - gdal=3.10
  - geopandas=1.1
  - rasterio=1.4
  - rioxarray=0.19
  - shapely=2.1
  - pyproj=3.7

  # File formats, file management, etc.
  - h5py=3.15
  - netcdf4=1.7
  - zarr~=2.18

  # Data and cloud access 
  - pystac=1.14
  - pystac-client=0.9
  - boto3=1.42
  - asf_search=12.0
  - pdemtools=1.2
  - s3fs>=2023.6.0

  # Parallel computing
  - dask=2026.1

  # Other useful generic stuff
  - pytest=9.0
  - tqdm=4.67

  # ISCE2 Dependcies
  - isce2=2.6
  - fftw=3.3
  - basemap=2.0
  - scons=4.10
  - opencv=4.13
  - conda-build=26.1

  - pip:
    - jupyter-keepalive
